import Bars from "@/components/bars";
import { ChatroomProvider } from "@/contexts/chatroom-context";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
    title: "Nara RAG",
    description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
    return (
        <ChatroomProvider>
            <div className="h-full w-full">
                <Bars />

                <main className="md:pl-[90] h-full w-full pt-[72] ease">
                    {children}
                </main>
            </div>
        </ChatroomProvider>
    );
};

export default RootLayout;
