pretrained_model_path: "./checkpoints/stable-diffusion-v1-4"
output_dir: "./outputs/camera"

train_data:
  video_root: "/home/LAMP/training_video/video_of_a_laptop_with_the_camera_orbiting_smoothly_from_left_to_right_around_it"
  #prompts: "video of a laptop, with the camera orbiting smoothly from left to right around it"
  n_sample_frames: 16
  width: 512
  height: 320
  sample_start_idx: 0
  sample_frame_rate: 1

validation_data:
  image_path: "/home/LAMP/experiment_dataset/camera"
  
  prompts:
    - "video of a laptop, with the camera orbiting smoothly from left to right around it"
  video_length: 16
  width: 512
  height: 320
  num_inference_steps: 50
  guidance_scale: 12.5
  use_inv_latent: False
  num_inv_steps: 50

learning_rate: 3e-5
train_batch_size: 1
max_train_steps: 30000
checkpointing_steps: 10000
validation_steps: 800
trainable_modules:
  - "conv1d"
  - "attn1.to_q"
  - "conv_gate"
  - "attn_temp"

seed: 33
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True